app = "prototyping-class-webapp"
primary_region = "gig"

[build]
[build.args]
GO_VERSION = "1.23.0"

[env]
DOMAIN = "https://prototyping-class-webapp.fly.dev"
PORT = "8080"
ENV = "prod"

[http_service]
internal_port = 8080
force_https = false
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[statics]]
guest_path = "/usr/local/bin/web/static"
url_prefix = "/static"

[mounts]
source = "user_data"
destination = "/data"

[[vm]]
memory = "1gb"
cpu_kind = "shared"
cpus = 1
